version: "3.5"

services:
    electricity-prices-dashboard:
        image: electricity-prices-dashboard
        container_name: electricity-prices-dashboard
        restart: always
        ports:
            - 3000:80
        networks:
            - elec-prices

networks:
    elec-prices:
        driver: bridge
        name: elec-prices
