name: Publish to Dockerhub

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish docker image to dockerhub
    permissions:
      contents: write
      pull-requests: write
      packages: read
    runs-on: self-hosted

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            daithihearn/electricity-prices-dashboard:latest
            daithihearn/electricity-prices-dashboard:${{ github.ref_name }}
          output: "type=registry,ref=$IMAGE_NAME:${{ github.sha }},name=manifest"
